### ISSUE TITLE
Make the Ethernet Segment (ES) a standalone entity

### ISSUE THREAD

**Issue by MotiMorg** [IETF-OPSAWG-WG/lxnm#327]
As it seems now, the ES is established as part of a specific VPN service, as well as configuring its member ports (which is performed on Network Access level) as part of a specific VPN service. However, a single ES entity is supposed to be used by multiple services (same as a physical port or a LAG that can serve multiple services). So, it should be decoupled from a specific VPN.
So, the correct approach would be handling the ES entity somewhat similar to the vpn-profiles. That is, the ES list should be decoupled from a specific VPN. It shall consist of a 'general' parameters-section, with all what we currently have in the Ethernet Segments Subtree, and a per Node section, where you can configure the ES members in various nodes.
Once you have the ES entities, multiple VPN service instances can utilize the same ES, each with a separate VLAN ID value.

**Comment by boucadair** [comment]
Thanks for the comment. 

We hesitated to position it at an upper level because of this language in RFC7432 (should):

```
   In general, an Ethernet segment SHOULD have a non-reserved ESI that
   is unique network wide (i.e., across all EVPN instances on all the
   PEs).  If the CE(s) constituting an Ethernet segment is (are) managed
   by the network operator, then ESI uniqueness should be guaranteed;
   however, if the CE(s) is (are) not managed, then the operator MUST
   configure a network-wide unique ESI for that Ethernet segment.  This
   is required to enable auto-discovery of Ethernet segments and
   Designated Forwarder (DF) election.
```
If we move it up, we may ensure uniqueness by design but this gives access to other ESIs not used by a given EVPN instance. I don't think whether that is an issue, but I'm mentioning it. I said "may ensure" because I don't know whether/how we can add a check (key) based on the ESI value given the assignment choices. 

The current design leaves it to the implementation to decide how to ensure uniqueness among all instances. 

I don't have an objection to move it up, but I hope to hear more opinions.

**Comment by MotiMorg** [comment]
Thanks for your quick response. 
I think the quoted text refers to the reduced importance of _ESI uniqueness_ when the Network provider also manages the CE(s). But, that does not contradict the assumption that the MH ES is a standalone entity. The MH ES does not "belong" to any specific EVPN service. The customer can utilize it for multiple EVPN services, same as he/she does when the CE connectivity to the provider is through a single port or LAG.

**Comment by boucadair** [comment]
@MotiMorg, @oscargdd, @sbarguil  please check the changes.
