### ISSUE TITLE
L3-NM: profile in bfd container should be at top level of container

### ISSUE THREAD

**Issue by julianL999** [IETF-OPSAWG-WG/lxnm#337]
At the moment, the BFD profile is invoked under "holdtime" in the BFD container. But typically, a BFD profile would contain other parameters as well, such as detection-multiplier etc. So it would be better to move the BFD profile up one level, so that there is a choice between  (i) specifying the value of all of the BFD parameters explicitly or (ii) invoking a BFD profile

**Comment by boucadair** [comment]
Hi Julian, 

FYI, this structure was initially inherited to ease the mapping with L3SM (RFC8299). The assumption is that the profile can include other parameters. 

I agree with you this is not clean and that it is better to have the profile apply for all parameters. However, if we go that way, this would not be defined as a choice because it is completely fine to have a profile listed + a set of customized parameters (that takes precedence if they were also part of the profile).

**Comment by boucadair** [comment]
Fixed in the candidate version https://github.com/IETF-OPSAWG-WG/lxnm/commit/7f0fb4e2d4579073cf1b23c63cab0124a76c9bc7
